### PR TITLE
Update & Delete Metrics Pages

### PR DESCRIPTION
**Pull request by jmsilverman**
There are multiple Metrics-related pages that are very out of date in DTMO:
-  [1.3. Terminology:DAU](https://docs.telemetry.mozilla.org/concepts/terminology.html#dau)
-  [2.2.9. Metrics](https://docs.telemetry.mozilla.org/cookbooks/metrics)
   -  [2.2.9.1. Daily Active Users (DAU and MAU)](https://docs.telemetry.mozilla.org/cookbooks/dau)
   -  [2.2.9.2. Active DAU (aDAU)](https://docs.telemetry.mozilla.org/cookbooks/active_dau)
   -  [2.2.9.3. Retention](https://docs.telemetry.mozilla.org/cookbooks/retention)

This PR removes the child pages and adds a link to the parent page to a single source of truth for metrics, which is the [Metrics Inventory](https://mozilla-hub.atlassian.net/wiki/spaces/DATA/pages/620494911/Metrics+Inventory) in Confluence.

This is part of [DS-3616](https://mozilla-hub.atlassian.net/browse/DS-3616).

### CODE REVIEW

**Review by bani — COMMENTED** [review]
Maybe we should have some broader discussions next week about the pros and cons of having open documentation and for which areas it's more important.

**Comment by jmsilverman** [comment]
@bani I think it'd be great to discuss this next week all together in Toronto, but the agenda is pretty full already (though we might be able to find some time to chat about it). I'll also point out that we have yet another a public-facing DAU description that is out of date: http://data.firefox.com/ (as well as a Jira ticket to fix that)

**Review by bochocki — APPROVED** [review]
This seems useful imo to clean up stale information and reduce the number of pages we need to maintain. It's worth having the conversation @bani mentioned though. It's possible we can do both -- have a single source of truth for documentation that is also publicly available.

Maybe it's worth talking about at the Methodology Working Group?

**Comment by jmsilverman** [comment]
After chatting about this at the Methodology Working Group meeting today it seems like we're agreed that it's OK to remove these pages. Also, on the metrics page, in addition to the link to Confluence's Metrics Inventory page, I added a link to metric-hub code in github (which is publicly accessible).

**Review by bani — APPROVED** [review]

**Review by bochocki — APPROVED** [review]

**Pull request merged**
