### PR TITLE
Update fxa email metrics

### PR DESCRIPTION
**Pull request by clouserw**

### CODE REVIEW

**Comment by clouserw** [comment]
I can't request review in this repository so pinging previous authors: @wlach @mreid-moz @irrationalagent   Sorry for the wide net.

It looks like the spell-check test is failing, but I'm not sure why.  Does it display what the failure is somewhere?

I'm the Engineering Manager for FxA and am planning on updating these docs as they are pretty out of date.  Is there a process for me to get write access to this area in the docs?

Thanks

**Comment by wlach** [comment]
> I can't request review in this repository so pinging previous authors: @wlach @mreid-moz @irrationalagent Sorry for the wide net.

I'm no longer at Mozilla but can try to help with a few things.

> It looks like the spell-check test is failing, but I'm not sure why. Does it display what the failure is somewhere?

I see this in the logs:

```
    src/datasets/fxa_metrics/emails.md
       47 | inked to a 3rd party account (eg. an Apple account)            
```

My guess is that it's your spelling of "eg.". There's some instructions on spell check stuff in the README: https://github.com/mozilla/data-docs#spell-checking

> I'm the Engineering Manager for FxA and am planning on updating these docs as they are pretty out of date. Is there a process for me to get write access to this area in the docs?

@mreid-moz or someone else from the data team should be able to help you here.

**Comment by jklukas** [comment]
Hi @wlach!

> @mreid-moz or someone else from the data team should be able to help you here.

I went ahead and added @clouserw with write privs for this repo so that you can add reviewers and create branches.

**Comment by clouserw** [comment]
> My guess is that it's your spelling of "eg.". 
Got it. I see there is an `e.g.` in the spelling file so I changed it to that.

This is passing now.  Thanks for the permissions; it looks like I can request review now.

**Review by irrationalagent — APPROVED** [review]
this LGTM. I did not verify that all of these templates / types are actually present in the code, since I am not close enough to the current state of FxA emails to do that. but the format and new descriptions look appropriate otherwise.

**Comment by clouserw** [comment]
@irrationalagent I'm planning on updating the rest of the FxA docs here.  Are you the best person to ask for review?

**Pull request merged**
